pluginName = EDT DCSQueryMenuEx
providerName = NZT
editQueryCommandName = Редактор запроса...
editQueryCommandTooltip = Открыть запрос в полноэкранном редакторе
editQueryContextMenuLabel = Редактор запроса...